Improve release process
lf-edge/adam pull request #131
Opened 2024-11-25 15:53 UTC by uncleDecart

This PR is RFC. It introduces doc, describing release process and changes to gha to publish release to ghcr.io as well as to dockerhub. The process described in the doc is similar to what we are doing in Eden and EVE, that way we can be consistent across repos

2024-11-25 19:09 UTC, deitch requested changes
Minor change to simplify the flow.

Thank you especially for the docs.

2024-11-25 19:09 UTC, deitch commented on .github/workflows/release.yaml
> +        uses: docker/build-push-action@v5
Save the trouble of building it multiple times. Just have multiple tags for all of them, including the ghcr.io tags. Sort of:

```yaml
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{env.IMAGE_NAME}}:${{env.GITHUB_REF#refs/tags/}}
            ${{env.IMAGE_NAME}}:latest
            ghcr.io/${{ github.repository_owner }}/adam:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository_owner }}/adam:latest
```

2024-11-26 15:47 UTC, deitch approved these changes

2024-11-26 15:47 UTC, deitch commented
LGTM. Ready to merge?

2024-11-27 09:02 UTC, uncleDecart commented
Yes, let's merge and then draft a release for v0.1.0 as a starting point

2024-11-27 09:27 UTC, yash-zededa approved these changes

2024-11-27 13:44 UTC, shjala commented
LGTM.

2024-11-27 14:46 UTC, merged